age=input("Enter Your Age")
print('Your Age Is',age)
num1=int(input("Enter 1st no"))
num2=int(input("Enter 2nd no"))
print(type(num1))
print(type(num2))
print('Sum Of 2 Nos',num1+num2)
num3=float(input("Enter 1st float no"))
num4=float(input("Enter 2nd float no"))
print(type(num3))
print(type(num4))
print('Product Of 2 Nos',num3*num4)
